### ISSUE TITLE
Question: Why is the unsubscribe function returned from subscribe not used?

### ISSUE THREAD

**Issue by wallw-dev** [Crisfole/react-use-svelte-store#2]
Without digging into the profiler too much, I imagine this would cause memory leaks.

A naive cut at what I'm asking about:

```typescript
export function useReadable<T>(store: Readable<T>): T {
    const [value, set] = useState<T>(unset as unknown as T);

    let unsubscribe: () => void;

    useEffect(() => {
        if (unsubscribe) {
            unsubscribe();
        }

        unsubscribe = store.subscribe(set);
        return unsubscribe;
    }, [store]);

    useEffect(() => unsubscribe, []);

    return value === unset ? get(store) : value;
}
```

If that's the case, I can make a PR. If not, could you please explain how the subscribers are removed?

**Comment by Crisfole** [comment]
@wallw-teal sorry for the slow reply here! I only just noticed this now that I started clearing out my extremely long notification list.

`useEffect` calls the function you return from it when the component it is used in is unmounted, or just before it reruns itself due to a dependency change.
