### ISSUE TITLE
Not Issue but Grateful

### ISSUE THREAD

**Issue by sonyarianto** [Crisfole/react-use-svelte-store#3]
Hi @Crisfole this package actually a productivity boost for me when using Next.js, thank you for this small but impactful package. Imagine in React I am struggling with re-render problem, and amazingly when I use this package properly, can make that problem goes away, makes me coding with Next.js great again hahahaha :) Thank you again.

Rather than using Zustand, Jotai, Redux or any other state management library. I choose svelte/store in combination with your react-use-svelte-store package, the combination is very powerful for me. I wonder why other people not use this approach. Hehehe :)

**Comment by Crisfole** [comment]
You're very welcome! Happy it's been helpful, it's not going anywhere (and even if it was the file is _VERY_ easy to copy and paste, which you should feel free to do).

I'm curious how Svelte 5 will impact this: Runes involve a compile step that are very different from how stores work.

If you're ever looking for something similar to this that doesn't add a dependency on Svelte you might wanna check out [`preact/signals`](https://github.com/preactjs/signals/tree/main/packages/react) as a replacement. I have *not* used this, but Signals and Stores are very similar and can be used for surgical UI updates.

**Comment by sonyarianto** [comment]
@Crisfole yeah, I think even if Svelte 5 change the store, I will stick with the old version of svelte/store package, since I only need the current version, is it OK right?
